# Generated by Django 5.0.1 on 2024-01-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "planning"),
                    ("B", "Block"),
                    ("D", "Doing"),
                    ("F", "Finish"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
