# Generated by Django 5.0.1 on 2024-01-14 04:01

from django.db import migrations, models


def task_is_finish_to_status(apps, schema_editor):
    Task = apps.get_model("todo", "Task")
    Task.objects.filter(is_finish=True).update(status="F")
    Task.objects.filter(is_finish=False).update(status="T")


def task_status_to_is_finish(apps, schema_editor):
    Task = apps.get_model("todo", "Task")
    Task.objects.filter(status="F").update(is_finish=True)
    Task.objects.exclude(status="F").update(is_finish=False)


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("T", "Todo"),
                    ("D", "Doing"),
                    ("W", "Waiting"),
                    ("F", "Finish"),
                ],
                default="T",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Planning"),
                    ("B", "Block"),
                    ("D", "Doing"),
                    ("F", "Finish"),
                ],
                default="P",
                max_length=1,
            ),
        ),
        migrations.RunPython(task_is_finish_to_status, task_status_to_is_finish),
        migrations.RemoveField(
            model_name="task",
            name="is_finish",
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("T", "Todo"),
                    ("D", "Doing"),
                    ("W", "Waiting"),
                    ("F", "Finish"),
                ],
                default="T",
                max_length=1,
            ),
        ),
    ]
