# Generated by Django 5.0.1 on 2024-01-14 05:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_remove_task_is_finish_task_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"permissions": [("archive_project", "Can archive project")]},
        ),
    ]
