# Generated by Django 4.2.7 on 2023-12-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0002_post_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
