# Generated by Django 4.2.7 on 2023-12-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0003_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(default="unknown", max_length=255),
            preserve_default=False,
        ),
    ]
