# Generated by Django 4.2.7 on 2023-12-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0004_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_draft",
            field=models.BooleanField(null=True),
        ),
    ]
